### ISSUE TITLE
Save pandas table to png

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#25]
Hi all,

You may refer to the following:

https://predictivehacks.com/?all-tips=save-a-pandas-dataframe-as-an-image

**Comment by sy25wang** [comment]
Great resource! Have updated the README.md to add this new dependency. Will create the pull request.
Thank you

**Comment by thomassiu** [comment]
Archive this issue
