### ISSUE TITLE
Testing functions

### ISSUE THREAD

**Issue by RamiroMejia** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#29]
We should discuss how can deal with this problem. It might be hard to add significant tests to the functions.

**Comment by RamiroMejia** [comment]
I added asserts for my functions. Are we supposed to create other functions that we are calling from sklearn ?

**Comment by thomassiu** [comment]
I just did some tests... 
If we put these functions in docpot files, we cannot test it, as there is no way we can call individual functions except using command line for the main. So my conclusion is... we cannot test.

**Comment by thomassiu** [comment]
FYI I used pytest as suggested by Tiffany.

**Comment by thomassiu** [comment]
Added by Ramiro in commit c4d25b3
