### ISSUE TITLE
Move report/ to doc/

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#36]
Hi Jasmine,

Can you move the files under report/ folder back to doc/?

**Comment by jasmineortega** [comment]
Tiffany had hers under report! Is there a reason we should move it

**Comment by thomassiu** [comment]
<img width="801" alt="brest cancer" src="https://user-images.githubusercontent.com/42147364/143668201-dbbc5d8e-f439-44be-a3ff-11c5fa169ab2.png">

can you check again ... her reports are all under doc/ and there isn't a folder called reports/. We can either rename it from doc/ to reports/ or we use doc/ ... I'm open to it

**Comment by jasmineortega** [comment]
It was in the breast cancer example!
https://github.com/ttimbers/breast_cancer_predictor/tree/master/doc

**Comment by jasmineortega** [comment]
It's okay I'll just move it

**Comment by thomassiu** [comment]
Main point is to put things that is for final audience in the same folder =D

**Comment by jasmineortega** [comment]
Fair enough. Done!
