### ISSUE TITLE
Clean folder Content

### ISSUE THREAD

**Issue by sy25wang** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#37]
For milestone 4, we should clean some of our folders, especially /src
- Move .ipynb files from milestone 1 to /src/raw folder
- Create flowchart folder for diagram and flowchart
- Other cleaning actions if necessary

**Comment by thomassiu** [comment]
As per our discussion this will be the tasks for milestone 4.

**Comment by thomassiu** [comment]
Let's discuss that during our final lab section.

**Comment by RamiroMejia** [comment]
I agree, I suggest removing all jupyter nb

**Comment by sy25wang** [comment]
Plan to do

- Move the following from /src to /src/raw
- [ ] Crime_in_Vancouver_eda.ipynb
- [ ] modelling.ipynb
- [ ] data_cleaning.ipynb
- [ ] data_cleaning_script.ipynb
- [ ] **rename** crime_vancouver_eda.py to crime_eda_script.py

**Comment by sy25wang** [comment]
- Create flowchart folder and move the following from /src to /flowchart
- [ ] diagram.xml
- [ ] flow_chart.png

**Comment by thomassiu** [comment]
This is completed as per #78
