### ISSUE TITLE
Grab files from Kaggle

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#4]
As Kaggle requires authentications before downloading the file, there is a way of streamlining the process by utilizing the Kaggle API.

**Install the Kaggle API** (Refer to the [Kaggle API page](https://github.com/Kaggle/kaggle-api) )
1. Install the Kaggle api by `pip install kaggle`
2. Sign up for a Kagge account at `https://www.kaggle.com`
3. Go to the `Account` tab of your user profile
4. Select `Create New API Token` under `API` session. This will trigger the download of `kaggle.json`.
5. Place the file in the location `~/.kaggle/kaggle.json` (on Windows in the location `C:\Users\<Windows-username>\.kaggle\kaggle.json`

**Run Kaggle API in python** (Refer to [StackOverflow](https://stackoverflow.com/questions/49386920/download-kaggle-dataset-by-using-python) )

Use the following code:
```python
import kaggle

data_url = 'kaggle_username/dataset_name'
data_path = 'your_local_path'

kaggle.api.authenticate()
kaggle.api.dataset_download_files(data_url, path=data_path, unzip=True)
```

Example:
To download the data of [Crime in Vancouver](https://www.kaggle.com/wosaku/crime-in-vancouver), set `data_url = 'wosaku/crime-in-vancouver'`.

**Comment by thomassiu** [comment]
Hi Jasmine,

Probably we can add this as a step of the contribution file.

Thanks
Thomas

**Comment by thomassiu** [comment]
I'm now including it as the README.MD, so we can instead reference the steps from contribution file to README instead.

**Comment by jasmineortega** [comment]
Hi Thomas,

Sorry -- to clarify, I don't need to add this to the contribution file and can direct to the README.instead?

**Comment by thomassiu** [comment]
Yes, just refer them back to the README for the steps =)

**Comment by jasmineortega** [comment]
Done. Thanks!

**Comment by thomassiu** [comment]
Thanks! Issue closed.
