### ISSUE TITLE
RandomGridCV - memory leak

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#42]
Hi,

If I include data from 2011 to 2020, the RandomGridCV throws a memory leak. Therefore I would suggest to further limit the data set from 2016 to 2020 only.

Corresponding changes are done in split_data.py and crime_vancouver.Rmd. Pending final check of the script before PR.

**Comment by jasmineortega** [comment]
Updated the literate code doc.

**Comment by thomassiu** [comment]
#44 closes this issue.
