### ISSUE TITLE
TODO: EDA contents and discussions

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#5]
Hi all,

Let's perform some more EDA on our own such that we can produce some graphs and tables. To be discussed on Nov 20 morning catch up.

**Comment by thomassiu** [comment]
Hi all,

As discussed in the meeting, I'd propose to have our own EDAs to be in our forked repo. Please add your repo link here.

**Comment by jasmineortega** [comment]
My EDA is in a branch in my repo
https://github.com/jasmineortega/DSCI_522_Crime_Prediction_Vancouver/tree/jasmine/src/Jasmine_EDA

**Comment by RamiroMejia** [comment]
MY EDA

https://github.com/RamiroMejia/DSCI_522_Crime_Prediction_Vancouver/blob/main/EDA.ipynb

**Comment by thomassiu** [comment]
This is my EDA - basically just a table format and added a bit of title and procedures.

https://github.com/thomassiu/DSCI_522_Crime_Prediction_Vancouver/tree/thomas_eda/src

**Comment by thomassiu** [comment]
Completed EDA hence closing this issue.
