### ISSUE TITLE
Milestone 1 Feedback corrections

### ISSUE THREAD

**Issue by RamiroMejia** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#57]
1. A+
2. A+
- ~don't need 522 in the repo name~
- ~the licence should be copyrighted to **your names** not MDS (it is your work)~
3. A-
- ~Your question is not quite clear to me. What exactly is the supervised learning model going to predict? I.e. what are the class labels? Given a neighbourhood/time/etc are you going to predict whether a crime will happen? or what type of crime will occur (given that you know some crime has occurred)?~ closed by Thomas
4. A+, A
- ~so is `zip_file_name` the name of the _unzipped_ file?~
5. A+, A-, A, A- (a,q,v,r)
- ~I don't know what "peak of data" means in this context~
- ~format dates in figures (remove commas)~
- ~Is midnight the placeholder for "no time recorded"?~
- ~You've found the neighbourhoods with the most crime and the most common crimes, how will this be used in your model?~
6. A+

**Comment by jasmineortega** [comment]
I PR'd my changes and I think that's the last of the corrections!

**Comment by thomassiu** [comment]
Thanks!

**Comment by RamiroMejia** [comment]
closed
