### ISSUE TITLE
Milestone 4 Goals

### ISSUE THREAD

**Issue by RamiroMejia** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#64]
## Milestone 4 objectives:

1.  Create a dependency diagram of the Makefile using `makefile2graph` and include it in the `README.md` file.

2.  Wrap up the project in Docker container
     -  Write a Docker file
     - Use Docker Hub Automated Build to build your Docker image from your Dockerfile
     - Include instructions in the project `README`
    
3.  Add a new comment in the issue where we received the feedback from other students.

**Comment by thomassiu** [comment]
Let's also update the suggestions we picked here:

https://github.com/UBC-MDS/data-analysis-review-2021/issues/8
